# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a994cd509d418ceb92fb92233d819a3d97206fa003c8148abfcdf40b4f76a1f77ba8b5075c42f0ccac4fc7456b65da9f9891fd70756ea38c3b7419f953372023

test:
  secret_key_base: 5ebd66e4da941cdeab64707eb378ab69f2ccff79f90ab80b6d7fe654d25e348b74127347a60a11cd3dcb53b96c54cf8f1bba7d05bbd4d63b90ea29e441d08b1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
